### ISSUE TITLE
导入账号密码问题

### ISSUE THREAD

**Issue by zhisiying** [cjxhaaa/cookies_pool-personal-#1]
path = 'sina97条账号密码.txt'
账号密码是存储在这里吗？
是用什么样的格式存储

**Comment by cjxhaaa** [comment]
> path = 'sina97条账号密码.txt'
> 账号密码是存储在这里吗？
> 是用什么样的格式存储

抱歉，我现在才注意到提问。账号密码确实是从这个文件导入的，格式我也忘记了。。不过这个项目太久没有维护了，可能现在新浪反爬以及接口应该都会有更新，应该爬取不到什么了，代码可以当做参考吧
